title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          title:
            label: Title
            type: text
            required: true

          breadcrumbTitle:
            label: Breadcrumb Title
            type: text
            help: Optional - how this page appears in breadcrumbs (defaults to page title)

          body:
            label: Body
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

