title: Default Page

icon: page

status:
  draft: true
  listed: true
  unlisted: true

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          blocks:
            label: Content
            type: blocks
            fieldsets:
              - heading
              - text
              - markdown
              - image
              - gallery
              - video
              - quote
              - code
              - list
              - columngrid
              - twocolumn
              - alert
            help: Build your page content using blocks

  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          pagecolor:
            label: Page Color
            type: text
            help: RGB values (e.g. "100, 100, 100")
            placeholder: "100, 100, 100"

      pages:
        type: pages
        template: default

      files:
        type: files

